requiered-players: 1
countdown-seconds: 30
lobby:
  world: 'world'
  x: 514
  y: 66
  z: 888
  yaw: 60.0
  pitch: 60.0
arenas:
  '0':
    world: 'world'
    x: 518
    y: 64
    z: 852
    yaw: 60.0
    pitch: 60.0
  '1':
    world: 'world'
    x: 492
    y: 63
    z: 876
    yaw: 60.0
    pitch: 60.0
  '2':
    world: 'world'
    x: 527
    y: 61
    z: 909
    yaw: 60.0
    pitch: 60.0